import Navbar from "@/components/Navbar";
import "./globals.css";
import { Inter } from "next/font/google";
import { Footer } from "@/components/Comp";
import { ClerkProvider } from "@clerk/nextjs";
import { GlobalContextProvider } from "@/Context/Store";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <Navbar />
          <GlobalContextProvider>

          {children}
          </GlobalContextProvider>
          <Footer />
        </body>
      </html>
    </ClerkProvider>
  );
}
